FROM mysql:8.0.20

ENV MYSQL_USER=keycloak \
    MYSQL_PASSWORD=keycloak \
    MYSQL_DATABASE=keycloak \
    MYSQL_ROOT_PASSWORD=root

VOLUME /Users/kyle/git/waf_auth/mysql/kc_mysql:/var/lib/mysql

EXPOSE 3306